import type { Metadata } from "next";
import { /* Inter,  */ Saira } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const saira = Saira({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Azure DevOps Reference",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body className={saira.className}>{children}</body>
    </html>
  );
}
