name: CI Prod

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:    

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PNPM
        run: npm i -g pnpm
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"
      - name: Install Dependencies
        run: pnpm i
  
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: npm run test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v4
      - name: Run lint
        run: npm run lint
  
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v4
      - name: Run build
        run: npm run build
