name: Prod Azure CD

env:
  AZURE_CONTAINER_REGISTRY: azuredevopsref
  PROJECT_NAME: devops-azure-reference # registry repository name
  REGISTRY_URL: azuredevopsref.azurecr.io
  RESOURCE_GROUP: azure_devops_ref
  CONTAINER_APP: azuredevopsref

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Az CLI login
        uses: azure/login@v1
        with:
          # Login with OCID requires an App Registration and Managed Identity/Federated credentials
          # TODO: kräver denna app reg client id, får unathurized när jag försöker uppdatera appen
          client-id: ${{ secrets.AZURE_MANAGED_IDENTITIE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build image and deploy to Azure container app
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az configure --defaults acr=${{ env.AZURE_CONTAINER_REGISTRY }}
            az acr build -r ${{ env.REGISTRY_URL }} -t ${{ env.PROJECT_NAME }}:${{ github.sha }} .    
            az containerapp update -n ${{ env.CONTAINER_APP }} -g ${{ env.RESOURCE_GROUP }} --image ${{ env.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }}
