name: Prod Azure CD

env:
  AZURE_CONTAINER_REGISTRY: RopaOlleRegistry
  PROJECT_NAME: devops # registry repository name
  REGISTRY_URL: ropaolleregistry.azurecr.io
  RESOURCE_GROUP: devops
  CONTAINER_APP: olle2

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build image and deploy to Azure container app
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az configure --defaults acr=${{ env.AZURE_CONTAINER_REGISTRY }}
            az acr build -r ${{ env.REGISTRY_URL }} -t ${{ env.PROJECT_NAME }}:${{ github.sha }} .    
            az containerapp update -n ${{ env.CONTAINER_APP }} -g ${{ env.RESOURCE_GROUP }} --image ${{ env.REGISTRY_URL }}/${{ env.PROJECT_NAME }}:${{ github.sha }}
